// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdfC_iENliuNjybXcWQliV_Xku6EbeTcs',
    appId: '1:210635251249:web:17ebbeca22f46c205abf10',
    messagingSenderId: '210635251249',
    projectId: 'pushnotification-5d075',
    authDomain: 'pushnotification-5d075.firebaseapp.com',
    storageBucket: 'pushnotification-5d075.firebasestorage.app',
    measurementId: 'G-NM1P2WTVNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZmdAc4iQY8QzI7yDD2Q7gnsPxbOsolWs',
    appId: '1:210635251249:android:334d5bf95027f3485abf10',
    messagingSenderId: '210635251249',
    projectId: 'pushnotification-5d075',
    storageBucket: 'pushnotification-5d075.firebasestorage.app',
  );
  // 1:210635251249:android:334d5bf95027f3485abf10
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRSrafd8Y-E77oEWRUPnpsNRmLLaIaEdE',
    appId: '1:210635251249:ios:0cb17a698c44916e5abf10',
    messagingSenderId: '210635251249',
    projectId: 'pushnotification-5d075',
    storageBucket: 'pushnotification-5d075.firebasestorage.app',
    iosBundleId: 'com.firebaseNotification.firebaseNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRSrafd8Y-E77oEWRUPnpsNRmLLaIaEdE',
    appId: '1:210635251249:ios:0cb17a698c44916e5abf10',
    messagingSenderId: '210635251249',
    projectId: 'pushnotification-5d075',
    storageBucket: 'pushnotification-5d075.firebasestorage.app',
    iosBundleId: 'com.firebaseNotification.firebaseNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdfC_iENliuNjybXcWQliV_Xku6EbeTcs',
    appId: '1:210635251249:web:04272543a5ad01665abf10',
    messagingSenderId: '210635251249',
    projectId: 'pushnotification-5d075',
    authDomain: 'pushnotification-5d075.firebaseapp.com',
    storageBucket: 'pushnotification-5d075.firebasestorage.app',
    measurementId: 'G-0ZYQHBFSYB',
  );
}
